version: '3.8'

services:
  torrent-downloader:
    build: .
    container_name: torrent-downloader
    ports:
      - "80:80"
      - "6881-6891:6881-6891/tcp"
      - "6881-6891:6881-6891/udp"
    volumes:
      - ./downloads:/app/downloads
      - torrent_data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2'
    networks:
      - torrent-network

volumes:
  torrent_data:

networks:
  torrent-network:
    driver: bridge
